config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Routes for static_pages controller
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # Routes for users controller
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    member do
      get :followings, :followers
    end
  end

  # Routes for sessions controller
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Routes for account_activations controller
  resources :account_activations, only: [:edit]

  # Routes for password reset controller
  resources :password_resets, only: %i[new create edit update]

  # Routes for microposts controller
  resources :microposts, only: %i[create destroy]

  # Routes for relationship controller
  resources :relationships, only: %i[create destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<h3>Micropost Feed</h3>
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpg, image/gif, image/png' %>
  </span>
<% end %>

<script type="text/javascript">
$('#micropost_picture').bind('change', function() {
  var size_in_megabytes = this.file.size/1024/1024;
  if (size_in_megabytes > 5) {
    alert('Maximum file size is 5MB. Please choose a smaller file.');
  }
});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>  <!--Get current user only in Home page-->
<div class="stats">
  <%= link_to followings_user_path(@user) do %>
    <strong id="followings" class="stat">
      <%= @user.followings.count %> 
    </strong>
    following
  <% end %>
  <%= link_to followers_user_path(@user) do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>